apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-3gku
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-3gku
    app.kubernetes.io/part-of: tkwch-fix-0075-0024-app
  name: devfile-sample-3gku
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-3gku
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-3gku
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0024-tenant/tkwch-fix-0075-0024-app/devfile-sample-3gku@sha256:c2a7579797dfbd3b459b39b52414c1eb401214138255c1156ffc75580f4a33b6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
